name: 🚀 Start UI [native] iOS

on:
  push:
    branches:
      - feat-setup-fastlane
  pull_request:

jobs:
  deploy-ios:
    name: Build and deploy for iOS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Install iOS dependencies
        run: cd ios && bundle exec pod install

      - name: Build & deploy Android release
        run: cd ios && bundle exec fastlane ios release
